<?php
$__information['ndskshortcut_list__pre'] = " 各ページLXADMINの右上隅には、[/ B] [B]のコレクションのようにこのページを追加するには、[B]の好みに追加をクリックすることができます[/ B]インチあなたはすることができます複数のページにショートカットリンクを追加し、[B]のコレクションの好みに[/ B]ページ、各リンクを標識するのに分けることができ、ソート。最初の行では、ツールバーは、すべてのページの上部に表示されます。";
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "これはあなたの問題を解決するために、にログオンするためのパスワードを必要とせずにlxabs技術を可能にサーバーにキーlxabsを追加します。";
$__information['rawlxguardhit_list__pre'] = "オリジナルのログイン情報を記録する。顧客の複数のログイン失敗は、ログインに。あなたは、クライアントのログイン名を知っている場合は、ここで利用可能で、対応するIPアドレスを参照してください黒から削除するには拒否されますリストを削除するには、再度ログインを許可。";
$__information['login_pre'] = "<p> ようこそ <%programname%>  </p><p>コンソールにログインするには有効なログイン名とパスワードを使用してください。 </p> ";
$__information['tickethistory_addform__pre'] = "使用可能 &#91quote&#93 &#91/quote &#93 コードを表示するには &#91code&#93 &#91/code&#93 コードを表示； &#91b&#93 &#91/b&#93 大胆。";
$__information['lxguardwhitelist_addform__pre'] = "あなたはできます<url:a=list&c=lxguardhitdisplay>Connections Page</url>ホワイトリスト管理ログインを手動で入力する必要がある場合は、必ず正しいIP作ります。";
$__information['sshconfig_updateform_update_pre'] = "パスワードの資格情報を無効にするには、してください<url:goback=1&a=list&c=sshauthorizedkey>SSHログイン認証</url>それはあなたがユーザのログインを指定することができます。 HyperVMプラットフォームとして、唯一のrootユーザのパスワードを防ぐことができます。LXADMINので、グローバルに設定することができた場合。";
$__information['all_dns_list__pre'] = "この<url:o=general&a=updateform&sa=reversedns>ページ</url> DNSサーバの顧客がHyperVMを通じ​​て、自分を追加できるように構成することができます。";
$__information['actionlog_list__pre'] = "アクティビティログが記録されているので、メインのログインを公開しないでください。<url:a=list&c=auxiliary>認識名</url>代替。";
$__information['sshauthorizedkey_list__pre'] = "中の~/.ssh/authorized_keys fileファイルには、サーバー管理にログインするためのパスワードなしで、ユーザーのキーを持って、リストの合理化を保つ。~/.ssh/authorized_keys2のみOpenssh第三版本。";
$__information['updateform_forcedeletepserver_pre'] = "サーバーが利用できなくなった場合には、HyperVMのレコードが削除されたデータベースから削除するように強制することはできません。";
$__information['allowedip_addform__pre'] = "注：コントロールパネルにログインすることを拒否、あなたは完全なすべてのIPは、* * * *または空白の書き込みを許可するよう、すべてのリソースへのアクセスを拒否されることはありません。このよう192.168として、IPのセットすることができます.... 0.1 *;「など192.168.1.2のようにIPを、指定された許可。";
$__information['blockedip_addform__pre'] = " 注：コントロールパネルにログオンを拒否する、完全なすべてのIPを許可するよう、すべてのリソースへのアクセスを拒否されることはありません、ここで入力してくださいIPへのアクセスを拒否する必要があります。";
$__information['updateform_portconfig_pre'] = "LXADMIN / HyperVMログインポートの変更を設定、エフェクト実行可能なコマンドを取るためにサービスを再起動する必要があり、 [b] cd /usr/local/lxlabs/<%program%>/httpdocs ; lphp.exe ../bin/common/misc/defaultport.php [/b] デフォルトのログインポートに戻すためにサービスを再起動してください。";
$__information['updateform_schedule_conf_pre'] = "ちょうど[b] <%program%>-scheduled- [/b]バックアップ計画の実行サイクルは、手動でバックアップを作成する場合、使用[b] <%program%>-scheduled- [/b]の命名方式。";
$__information['updateform_ssl_lxadmin_pre'] = "これは<%program%>完成された、SSL証明書の設定、再起動<%program%>。";
$__information['updateform_ssl_authorized_keys_pre'] = "SSHキーログイン、パスワードなしの設定には、セキュリティを強化することができます。 1行に1つずつは、潜在的なリスクを軽減するために、できるだけ少しを承認してください。";
$__information['updateform_ssl_hypervm_pre'] = "これは<%program%>完成された、SSL証明書の設定、再起動<%program%>。";
$__information['updateform_selfbackupconfig_pre'] = " プライマリサーバ上のデータベースのバックアップ設定のためのみ。マシンに格納されたデータベースのデフォルトの日次バックアップのFTPアカウントを設定している場合、リモートFTPサーバーにアップロード保存されます。";
$__information['lxguard_updateform_update_pre'] = " 保護者のLXの役割は、SSHを防ぎ、ブルートフォースをftpにあります。誰かがパスワードのftpまたはsshを列挙しようとすると、エラーの累積数は、ブラックリストにされます。この機能は無効にすることはできませんが、失敗したログインまたはホワイトリストの許容数を調整することができます。 Lxのガーディアンの役割のヒントを閉じるには、隣にあるチェックボックスをオンに。";
$__information['updateform_generalsetting_pre'] = " デスク - お気に入りのプログラムへのリンクではなく、Lxが来ます。同様に、あなたは自分のアドレスログインを設定することができます。";
$__information['custombutton_addform__pre'] = "URLアドレスでは、使用することができます%nname%対応する顧客を表現するために、%default_domain%デフォルトのドメイン名であります。";
$__information['updateform_download_config_pre'] = "一般的に、ファイルをダウンロードするプロセスでは、セッションをオンにするための唯一の責任マスターサーバーは、その後、セカンダリサーバからファイルをダウンロードし、帯域幅を保存することができますが、セカンダリサーバが直接インターネットにアクセスすることができない場合は、有効にした場合エントリー、マスターサーバーによるファイル転送。";
$__information['updateform_login_options_pre'] = " 注：セッションタイムアウトが100未満などの設定、100デフォルト、100以上です。";
$__information['resourceplan_change_pre'] = " 注意：あなたが影響を受けることになりますすべての顧客にプログラムを使用して、設定値をプログラムに変更を加えた場合。クリックします<url:a=updateForm&sa=account>ここに</url>プログラムの表示ユーザー。";
$__information['lxbackup_updateform_backup_pre'] = " ファイルマネージャで、__backupディレクトリは、バックアップファイルを保存することです。復元するには、[アップロード]タブのファイルもソースHTTPやFTPアドレスを指定できますクリックして、あなたはまた、指定したファイルを選択することができ、事前スタートを復元するために復元]ボタンをクリックしてください。注意してください、<%program%>バックアップは、ツリーで、adminなど過度のバックアップとして、顧客はもはや、バックアップ管理者の名前を行う必要がありません。";
$__information['phpini_updateform_edit_admin_pre'] = "LXADMINは、PHPの設定ファイルを管理する既存の設定ファイルを上書きしますPHPの設定をチェックするために復元するために、選択を解除してください。";
$__information['client_updateform_wall_pre'] = " 注：このメッセージは、唯一の直接顧客に送信されます（このアカウントを含む）連絡先メールアドレスの入力を";
$__information['ffile_updateform_upload_pre'] = " ファイルマネージャをアップロードした後解凍最初のzipファイルに、ファイルやディレクトリを複数アップロードするには。";
$__information['dskshortcut_a_list__pre'] = " あなたは、頻繁に、フォルダを好きな名前を定義し、名前でソート可能なクリックを保存し、左のソートに使用追加できるページが変更されます。";
$__information['ticketconfig_updateform_ticketconfig_pre'] = "メールゲートは、<％program％>が特定の間隔でメールをダウンロードし、解析されてヘルプデスクに追加されるアカウントです。 メールを送信するとき、<％program％>は設定したアドレスから送信されたものとしてメールを送信します。 アドレスは[b] account@domain.com [/ b]の形式です。 Serverはメールをダウンロードするポップサーバーです。 [b] server.com [/ b]。 [b] use ssl [/ b]チェックボックスをオンにすると、ポート995のpop3-sslを介してメールがダウンロードされます。常にsslを使用することをお勧めしますが、リモートメール sererはポート995でpop3-sslサービスをサポートします。";
$__information['updateform_mysqlpasswordreset_pre'] = "これは、rootパスワードを紛失した場合にのみ使用してください。 通常は、<url：a = list＆c = dbadmin>（データベース管理者）</ url>をクリックしてパスワードを変更できます。 これが完了するまでに時間がかかるので、忍耐してください。 これは、mysqlのルートパスワードをskip-grant-tablesオプションで実行してリセットします。 これでうまくいかない場合は、sshでログインし、../bin/common/misc/reset-mysql-root-password.phpを実行してください。 ";
$__information['updateform_pserver_s_pre'] = "これは、この再販業者のサーバープールです。 これは、このリセラーがクライアントの作成時に使用できるサーバーのリストを示します。 つまり、新しい顧客を作成する場合、このリセラーはこのリストのサーバーを自分に割り当てることができます.";
$__information['general_updateform_disableper_pre'] = " これは、アカウントを無効にする使用率です。 正常値は110％です。 クォータが90,100,110％に達すると、警告が表示されます。 ";
$__information['updateform_ftp_conf_pre'] = "あなたが設定されている場合は、 [b] ローカルコピーが削除され、 [/b], のローカルコピーを保持しません。あなたがスペースを節約したい場合は、ローカルコピーを保持しないことを選択することができます";
$__information['vv_updateform_skin_logo_pre'] = " ユーザーのあなたの次のレベルにあなたのロゴを表示したい、で彼らのエネルギー管理のロゴの権利管理機能をキャンセル. ";
$__information['pserver_updateform_information_pre'] = "FQDNは、非常に重要な地域であることは、ドメイン名に設定する必要があり、適切にこの特定のマシンに対処します。あなたがFQDNを設定したらFQDNがここで設定した場合、hyperVMは、ネットワークマスタ/スレーブとの間の通信が失敗する運命に、間違っている、この値はすべての通信ネットワークを使用します。空白にした場合、hyperVMがこのサーバー上での通信に最初のIPアドレスを使用します。あなたはどこからでもで本機を使用することができ、これらを使用するホストのFQDNを設定します。。";
$__information['pserver_addform__pre'] = "スレーブサーバーを新しくインストールした場合、パスワードはadminです。 サーバーをIPではなく名前で追加することを強くお勧めします。 サーバーここで指定した特定の名前（server.domain.comなど）を使用して、マスターからアクセス可能である必要があります。 verbose-identifierは、このサーバを記述するために使用できる文字列であり、セレクタボックスに表示されます.";
$__information['updateform_upload_logo_pre'] = " 空白のロゴ画像を残すことは、デフォルトとして設定されます。あなたは、ユーザーの次のレベルは、あなたのロゴを表示して彼らの "エネルギー管理のロゴの権利管理機能をキャンセルしたいです. ";
$__information['web_updateform_extra_tag_pre'] = " <b><font color=red> 警告!!!!! </font></b>  ここで入力したかどうかは、仮想ホストに直接追加されます。構文エラーがある場合は、ネットワーク・サーバを再起動することはできません防ぐことができます。このオプションは、管理者ユーザのためにのみ利用可能です。ここで保存するために、サーバーが実行されていることを確認。 ";
$__information['addondomain_list__pre'] = " ノート: <br>* あなたはそれがすべてのDNSやメールの管理を楽しむように、ドメイン名をバインドしたい場合は、完全なドメインが同じドキュメントルートを持っている確立することは、対象ドメインであります <br> *あなたがドメイン名をリダイレクトしたい、それが完全なドメイン名を作成するには、完全なDNSとメール管理を楽しんでいた場合は、その設定[b] / [/b]Directoryドメインに";
$__information['redirect_a_list__pre'] = "これにより、ドメイン内の特定のURLを別のURLにリダイレクトすることができます. <url:a=updateform&sa=configure_misc> Click here </url> www以外のベースを強制的にリダイレクトする場合 http://domain.com to http://www.domain.com, ";
$__information['web_updateform_dirindex_pre'] = "[b]ディレクトリインデックス[/ b]を有効にすると、Webサーバー経由でドメインのディレクトリを参照できます。 ディレクトリインデックスが無効で、index.xxxファイルがディレクトリ内に見つからない場合は、禁止されたエラーメッセージが表示されます。";
$__information['updateform_editmx_pre'] = " リモートメールサーバーを構成する場合は、 <url:a=updateform&sa=remotelocalmail> Click here </url>. lxadminに、メールサーバーがリモートで構成されていることを伝えると、ローカルで生成されたすべてのメールがそのサーバーに送信されます。 リモートメールを設定しないと、このドメインへのすべてのメールは、DNSルックアップを行うことなく、ローカルで配信されます。 ";
$__information['web_updateform_run_stats_pre'] = "これにより、強制的に統計プログラムを実行できるようになります。これにより、Web統計ページで最新の統計情報を確認できます。 [b]すべて更新[/ b]を使用して、トッププルダウンメニューに表示されているすべてのドメインでそれを実行します。";
$__information['server_alias_a_addform__pre'] = "エイリアスとして[b] * [/ b]を追加すると、すべてのサブドメインが自動的にこのドメインに誘導されます。 LxadminはエイリアスのDNSエントリも自動的に追加します。 キャッチオールのサブドメインに '*'を設定したら、適切なロジックをスクリプトに追加して正しいサブドメインを検出し、それに応じて行うことができます。";
$__information['updateform_sesubmit_pre'] = "あなたのドメインは、下記のすべての検索エンジンに提出されます。 あなたがここに入力したメールに迷惑メールを発する可能性が非常に高いので、頻繁には使用されないアドレスでなければなりません";
$__information['mmail_updateform_authentication_pre'] = "プライマリmxサーバは自動的にSPFに組み込まれており、別途追加する必要はありません。 [b]すべて更新[/ b]を使用して、トッププルダウンリストに表示されているすべてのドメインのこれらの値に印を付けることができます。";
$__information['updateform_preview_config_pre'] = "プレビュードメインはマスタードメインで、サイトプレビューボタンがリダイレクトされます。 domain.com.previewdomain.comというパーキングドメインをこのドメインに手動で追加し、ここにpreviewdomain.comを追加する必要があります。 [b] dns lessプレビュー[/ b]はdomain.com.previewdomain.comにリダイレクトされます。 不明な場合は空白のままにしてください。";
$__information['updateform_stats_protect_pre'] = "統計ページ保護は、ドメインの統計ページを保護するために使用されるパスワードです。 パスワードをnullに設定すると、保護が無効になり、統計に直接アクセスすることができます。";
$__information['ftpuser_admin'] = "[b] --direct-- [/ b]を使用して、ドメイン名を含まないftpuserを追加します。";
$__information['updateform_default_domain_pre'] = " これにより、この特定のアカウントのプライマリドメインとみなされるドメインが設定されます。 このドメインのドキュメントルートには、http：// IP /〜clientnameにアクセスしてアクセスできます。 ipaddressをドメインにマッピングするには、<url：a = list＆c = ipaddress>ここをクリック</ url>し、ipaddressの中に入り、そこに 'Configure domain'タブをクリックします。 dnsが設定される前にドメインを表示する場合は、ローカルのetc / hostsファイルにドメインのエントリを作成することをお勧めします。 Windows上のファイルのパスはc：/ windows / system32 / drivers / etc / hostsです。 separete行に[b] 192.168.1.32 domain.com [/ b]のようなエントリを追加するだけで、ブラウザのURLボックスにドメインにアクセスすることができます。";
$__information['updateform_blockip_pre'] = " 1行に1つのIPを追加します。 IP範囲を追加する場合は、.*.*表記を使用します。 例えば、192.168.*.*. これはip範囲でサポートされている唯一の記法です。 標準のip表記はサポートされていません。";
$__information['web_updateform_statsconfig_pre'] = "毎日、ログファイルのサイズが50MBより大きい場合、それらはクライアントのホームディレクトリに移動されます。 remove_processed_logsをtrueに設定すると、移動する代わりに削除されます。 主な統計計算にはまったく影響はありません。";
$__information['web_updateform_hotlink_protection_pre'] = "ドメインとサブドメインは自動的に画像にアクセスできるため、特別に追加する必要はありません。 a * .domain.comは、ここで指定した許可ドメインのリストに自動的に追加されます。 [b]イメージへのリダイレクト[/ b]は、ドメイン内のイメージへのパスでなければならず、完全なURLではありません。 フォームは（/img/noaccess.gif）にする必要があります。 あなたは野生の文字なしで単純な名前としてドメインを入力する必要があります。 たとえば、domain.com、mydomain.com、mysdomain.comなどです。";
$__information['mailqueue_list__pre'] = "キューが実際に消えるまで少し時間がかかります。 だから、削除をクリックすると、メールはもう少し待ち行列に表示されます。 メールが実際に削除されたかどうか確認するために、ちょうど約1分後にページを更新してください。";
$__information['mailqueue_updateform_update_pre'] = "メールのログを見るには、リストに戻って、過去1時間のログだけが解析されるので、メールキューを一度フラッシュしてください。";
$__information['rubyrails_addform__pre'] = "通常、アプリケーションはhttp://domain.com/applicationnameからアクセスできます。 パスは/home/client/ror/domain.com/applicationnameになります。 [b]アクセス可能な直接[/ b]フラグを指定すると、アプリケーションはhttp://domain.com自体からアクセス可能になります。";
$__information['installsoft_addform__pre'] = "Toドキュメントルートにアプリケーションをインストールする場合は、[b] Location [/ b]を空白のままにしてください。 別のドメインに同じアプリケーションをインストールするには、上部の選択ボックスを使用してドメインを別のドメインに変更してください。新しいドメインを親として同じフォームを取得することができます。 ログイン情報とURL情報が記載されたメッセージが、ここで提供する連絡先電子メールアドレスに送信されます。";
$__information['mysqldb_updateform_restore_pre'] = "これは、[b] Get Backup [/ b]タブを使用して明示的にLxadminで取得したバックアップをリストアする場合にのみ使用できます。 通常のmysqlダンプファイルを復元するには、phpMyAdminを使用してください。";
$__information['domainipaddress_updateform_update_pre'] = "これにより、特定のIPアドレスをドメインにマップすることができます。 つまり、誰かがhttp：// ipにアクセスすると、ここで設定されたドメインのドキュメントルートが表示されます。";
$__information['updateform_search_engine_pre'] = "一部のエンジンでは、送信のために電子メールの確認が必要な場合があります。 スパムメッセージを受信する可能性があるため、メインのEメールアドレスを入力しないでください。 あなたが禁止になるかもしれないので、より良いランク付けのために3〜4週間ごとに操作を繰り返すが、早くはない";
$__information['updateform_domainpserver_pre'] = "これらは、このクライアントの下のドメインが構成されるサーバーです。 ここで値を変更すると、自動的にすべてのドメインが適切なサーバーに移動されます。 つまり、[b]メールサーバー[/ b]を変更して更新すると、このクライアントの下にあるドメインのメールアカウントはすべて古いサーバーから新しいサーバーに移行されます。 [b] dnstemplate [/ b]は、すべてのドメインのDNSが切り替わる新しいdnstemplateです。 新しい構成を反映するdnstemplateを作成してから、ここでlxadminに提供する必要があります。 サーバー移動の詳細については、下を参照してください。 後で[b] dns manager - > rebuild [/ b]に行き、[b] update all [/ b]をクリックすることで、大量のDNSを後で変更することができ、アカウントのすべてのドメインに新しいdnstemplateが適用されます。";
$__information['sslipaddress_updateform_update_pre'] = "ipaddressにsslを設定するには、まず<url：goback = 2＆a = list＆c = sslcert>ここからSSL証明書をアップロード/追加します。</ url>";
$__information['domain_addform__pre_docroot'] = "ドキュメントのルートを空白のままにすると、Lxadminはmydomain.comを自動的にdocrootとして使用します。";
$__information['sslcert_updateform_update_pre_admin'] = "このssl証明書を特定のipaddressに割り当てるには、ipaddressに入り、[b]をクリックして、特定のipaddressにこのssl証明書を割り当てるには<url：goback = 1＆l [class] = pserver＆l [nname] = localhost＆a = list＆c = ipaddress> ssl certificate [/ b]タブをクリックし、これらの証明書のいずれかを特定のipaddressに設定することができます。";
$__information['sslcert_updateform_update_pre'] = "このssl証明書を特定のipaddressに割り当てるには、<url：goback = 2＆a = list＆c = ipaddress>ここをクリックして</ url>をクリックしてipaddressに入り、[b] ssl certificate [/ b] これらの証明書の1つを特定のipaddressに設定できます。 この機能にアクセスするには、管理者があなたに専用のIPアドレスを割り当てておく必要があります。";
$__information['domain_not_customer'] = "ドメインを追加するには、最初に顧客を作成し、その下にドメインを追加することができます。 顧客を追加するには、 <url:a=addform&c=client&dta[var]=cttype&dta[val]=customer>click here </url>";
$__information['ipaddress_list__pre'] = "Exclusive IPでは、特定のIPアドレスを専用に制御できます。 これは、SSLを設定する場合や、ドメインのIPを設定する場合に便利です。 つまり、特定のIPをドメインに解決したい場合です。 あなたは排他的なIPアドレスを持つために、管理者は特定のIPアドレスの排他的なクライアントを設定する必要があります。 sslをセットアップするか、IPをドメインにマップするには、IPアドレスをクリックし、[b] configure ssl [/ b]または[b] configure domain [/ b]";
$__information['clientmail_list__pre'] = "最後の2日間に、クライアントからWebサーバーまたはSMTP認証リレー経由で送信されたメールの数が表示されます。 [b] user@domain.com [/ b]のような完全なメールアカウントであれば、リレー経由で送信されたメールを表します。 単純なユーザー名であれば、Webサーバーのフォームを介して送信されたメールを表します。 Apacheでmod_phpを使用すると、すべてのWebアプリケーションはuser [b] apache [/ b]として実行され、[b] apache [/ b]のみがここに表示されます。 サードパーティのホスティングを計画している場合は、ApacheでsuPHPを使用してください。 そうすれば、システムユーザを使って各クライアントを識別することができます。";
$__information['servermail_updateform_update_pre'] = "私の名前を適切に解決可能なホスト名に設定することは非常に重要です。そうしないと、hotmailのような多くの公開メールサーバがあなたのサーバからのメールを拒否するからです。 追加のポートでメールサーバーを実行させるには、ここで指定します。 空白のままにしておくと、追加のsmtpが無効になります。 max smtp instancesは、許可されるsmtpプロセスの最大数を指定します。 大量のスパムメールを受信している場合は、10に設定してください。 空白のままにすると、デフォルトであるUNLIMITEDに設定されます。";
$__information['updateform_switchprogram_pre'] = "古いプログラムをシステムから削除し、yumを使って新しいプログラムをインストールする必要があるため、プログラムの切り替えにはしばらく時間がかかります。 このログはshell_execファイルで利用できます。 すべての情報が透過的に移行されます。 新しいサービスが正常に再開するまでに1分待つ必要があります。";
$__information['updateform_permalink_pre'] = "Lxadminには、多くのアプリでデフォルトのパーマリンク設定が用意されています。 アプリケーションとそれをインストールしたディレクトリを選択してください。lxadminは対応する書き換えルールを軽い設定に追加します。 いくつかのアプリケーションでは、permalinkは404エラーハンドラ（wordpressなど）を設定することによって実現されることに注意してください。";
$__information['weblastvisit_list__pre'] = "これは最後の50人の訪問者のリスト、または過去20時間の訪問者のうち小さい方の人数です。 RealtimeはUnixのタイムスタンプの時刻を表しており、時刻によって正確にソートできるようになっています。 長い文字列は画面に合うように切り捨てられ、マウスの上にマウスを移動することで完全な値が表示されます。";
$__information['subweb_a_addform__pre'] = "これは単純なサブドメインです。 単純なサブドメインにはWebコンポーネントしかなく、メールの追加やDNSの管理はできません。 完全なサブドメインが必要な場合は、メイン[b]ドメイン[/ b]ページの[b]サブドメインボタン[/ b]を使用してください。 単純なサブドメインのパスは/home/clientname/domain/domain.com/subdomains/subdomainnameです。";
$__information['updateform_skeleton_pre'] = "これは、作成時にドメインのホームディレクトリにコピーされるスケルトンディレクトリのアーカイブです。 アーカイブは新しく作成されたドメインのホームディレクトリに解凍されます。 index.htmlファイル内で[b] <％domainname％>、<％clientname％> [/ b]を使用すると、変数は正しい値に正しく置き換えられます。";
$__information['updateform_lighty_rewrite_pre'] = "これは、変更なしで構成ファイルに直接追加されるカスタムのlighttpd書き換えルールです。 それは[b] url.rewrite =（... [/ b]の形式になります。";
$__information['updateform_custom_error_pre'] = "<p> 注意：提供する必要がある値は、これらのエラーの場合に表示されるファイルへの仮想パスです。 例：/error_files/404.html。</p>";
$__information['domain_updateform_ipaddress_pre'] = "<p> 注：ネームサーバー構成ツールに必要な変更を加えたことを確認してください。 </p>";
$__information['client_updateform_ipaddress_pre'] = "<p> 注：使用可能なIPプールは、Webサーバープール内のマシンから選択されます。 </p>";
$__information['domaintemplate_addform__pre'] = "<p> 注：右側の最大値には、現在の割り当て制限が表示されます。 クォータ以上の値を持つテンプレートを作成することはできますが、ドメイン/クライアントの作成には使用できません。 </p>";
$__information['vv_dns_blank_message'] = "<p> ベースドメインを取得する場合は、 '__base__'と入力します。 TXTレコード内にドメイン名を使用する場合は、<％domain>を使用します。 たとえば、 'v = spf1 include：<％domain>'です。 [b] FCNAME [/ b]は完全なcnameを表し、サブドメインを外部ドメインにポイントすることを許可します。";
$__information['spam_updateform_update_pre'] = "<p> 「スコア」（1-10）は、メールがSPAMとしてマークされている値です。 したがって、値を低く設定すると、より多くのメールがスパムとしてマークされます。 値が小さすぎると、本物のメールがスパムとして分類される可能性があります。 値が大きすぎると、フィルタを通過するスパムの量が多くなります。 </p>";
$__information['web_updateform_enable_frontpage_flag_pre'] = "<p> フロントページのパスワードは、システムユーザー（メインFTPユーザー）のパスワードと同じになります。</p>";
$__information['ffile_show___lx_error_log_pre'] = "これはあなたのドメインのエラーログです。 この内容は、ドメインに関する問題が発生した場合のトラブルシューティングに役立ちます。";
$__information['installappsnapshot_list__pre'] = "スナップショットは、データベースの正確なコピーと、特定の時間にアプリケーションのファイルです。 [b]リストア[/ b]ボタンをクリックすると、アプリケーションを特定のスナップショットに復元できます。";
$__information['sshclient_updateform_disabled_pre'] = "管理者がシェルアクセスを有効にしていません。 sshアクセスが必要な場合は、サポートチケットを開いてください。 ";
$__information['sshclient_updateform_warning_pre'] = "すべてのアクティビティが記録され、あなた以外のファイルにアクセスしようとすると、ホスティングアカウントが終了することに注意してください。 だから責任感を持って行動してください。";
$__information['ffile_show___lx_access_log_pre'] = "これはあなたのドメインのアクセスログです。 右の[b]ダウンロード[/ b]タブをクリックしてダウンロードできます。 このファイルには、あなたのウェブサイトに対して行われたすべてのシングルヒットに関する情報が含まれています";
$__information['updateform_disable_url_pre'] = "すべての子供は自動的にあなたのDisable URLパラメータを継承します。 自分のDisable Urlを強制するには、権限設定で 'Unset Disable Url'を無効にするだけです。 これは、ドメインが無効になったときにリダイレクトされるURLです。 ";
$__information['updateform_dnstemplatelist_pre'] = "顧客に単一のDNSテンプレートのみを割り当てます。 これは、ドメインを追加するときにlxadminがdnsテンプレートの選択ボックスを表示しないことを意味します。これにより、お客様には分かりにくくなります。";
$__information['forward_a_addform__pre'] = "転送先アドレスは、メールが転送される電子メールアドレスのリストです。 メールのコピーも実際のメールアカウントに保存されます。 ローカルストレージを無効にすることができます。 <url:a=updateform&sa=configuration>clicking here </url>.";
$__emessage['blocked'] = "あなたのアドレスは禁止されています";
$__emessage['no_server'] = "サーバーに接続できません。";
$__emessage['set_emailid'] = "メールアドレスのセット";
$__emessage['no_socket_connect_to_server'] = ".. [b]/スクリプト/再起動[/ b]：[%s]にログインし、LXADMINを再起動するか、SSH経由のLinuxツールに接続し、スクリプトを実行してくださいサーバーに接続できません";
$__emessage['restarting_backend'] = "再起動してください。再び30秒を試してみてください";
$__emessage['quota_exceeded'] = "クォータ超過 [%s]";
$__emessage['license_no_ipaddress'] = "このサーバのパブリックIPアドレス[％s]は、ライセンスリポジトリに見つかりませんでした。 このサーバーのライセンスを作成するには、Lxlabsセールスまたはリセラーにお問い合わせください。 </a> ";
$__emessage['ssh_root_password_access'] = "このサーバー上のrootへのパスワードベースのアクセスを無効にしていません。 rootにアクセスするためのパスワードベースのアクセスは必要ありません。これは、hypervm経由でssh認証キーを管理できるためです。 sshサーバを設定するには、<url：k [class] = pserver＆k [nname] = localhost＆a = updateform＆sa = update＆o = sshconfig>ここをクリック</ url>";
$__emessage['already_exists'] = "リソース（名前）[%s]に存在します。";
$__emessage['lxguard_not_configured'] = "Lxguard構成されていません。してください<url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard>点击这里配置 Lxguard </url> 。 R Lxguardは、それはまた、サーバなどに指定されたIPアドレスへのアクセスを遮断することができ、同時にサーバでのセキュリティ上の欠陥を見つけることです。";
$__emessage['root_cannot_extract_to_existing_dir'] = "rootユーザーが既に存在するディレクトリに圧縮されたパッケージを抽出することはできません。ディレクトリがすでに存在しています。システムに存在しないディレクトリの名前を入力してください";
$__emessage['no_imagemagick'] = "現在のシステムがインストールされていないのimagemagick。実行可能なシェルコマンドは、インストールします： [b] yum -y install imagemagick [/b].";
$__emessage['warn_license_limit'] = "あなたはライセンスの上限に非常に近いです： [%s]. システムがライセンスを超える場合 [%s] ，インターフェイスは動作を停止します、そして、あなたのシステムを管理することはできません。からライセンスまたは更新を増やします <url:o=license&a=show> ここに</url>";
$__emessage['file_already_exists'] = "The file [%s] もう存在している。";
$__emessage['contact_set_but_not_correct'] = "あなたの連絡先情報は有効なメールアドレスを思えません。ポイント <url:a=updateform&sa=information> ここに改正しました。</url> ";
$__emessage['contact_not_set'] = "あなたの連絡先情報が設定されていません。クリックしてください <url:a=updateform&sa=information> ここでは正しい。[コントロールパネルは理解していないものを、質問をフォーラムにアクセスしてください！] </url> ";
$__emessage['you_have_unread_message'] = "あなたは持っています [%s] 未読のメッセージ(s).  <burl:a=list&c=smessage> ここをクリックしてください。 </burl>";
$__emessage['you_have_unread_ticket'] = "あなたは持っています [%s] 未読 Ticket(s).  <burl:a=list&c=ticket> ここをクリックしてください。 </burl>";
$__emessage['security_warning'] = "あなたのパスワードは、現在の深刻なセキュリティ上の脅威となる一般的なパスワードとして使用されています。してください <url:a=updateform&sa=password> 修正するにはここをクリックしてください。 </url> ";
$__emessage['ssh_port_not_configured'] = "SSHサーバのポートが設定されていません。変更にもよりよいだろう場合は、デフォルトでは、デフォルトでは22ですが、。   <url:a=show&o=sshconfig> 変更するにはクリックしてください。</url>. それでも22ワードを保持したい場合は、また22の内容を変更、当然のことながら、外観を変更するので、あなたは、物品の迅速な情報を持ち続けるません";
$__emessage['system_is_updating_itself'] = "システムは自己更新され、この時点で、あなたは数分を変更することはできません。すべての読み取り操作が正常に動作することができます。";
$__emessage['system_is_locked'] = "誰かがまだ進行中のこの特定のオブジェクトに対してシステム変更アクションを開始しました。 あなたはそれが終わるまで変更を加えることはできません。 しかし、すべての読み取りアクションは正常に動作します。";
$__emessage['system_is_locked_by_u'] = "あなたはまだ進行中のシステム変更アクションを開始しました。 あなたはそれが終わるまで変更を加えることはできません。 しかし、すべての読み取りアクションは正常に動作します。";
$__emessage['smtp_server_not_running'] = "hyperVMは、このサーバー上のSMTPサーバーに接続できません。これはhyperVMは、任意のメールを送信しないことを意味します。ご質問があればhyperVMは、クラスタ全体の管理や電子メールの送信を監視するため、これは、非常に重要です。あなたは、SMTPサービスがこのサーバー上で実行されていることを確認する必要があります。あなたはSMTPサービスを再起動すると、5分待って、エラーメッセージが表示されなくなります、5分ごとに利用できるチェックサービスhyperVMので。";
$__emessage['template_not_owner'] = "このテンプレートの所有者ではありません";
$__emessage['ipaddress_changed_amidst_session'] = "IPアドレスは、セッションハイジャックがある可能性があり、セッション中に変更されました";
$__emessage['more_than_one_user'] = "アカウントのログイン複数のユーザー。ポイント <burl:a=list&c=ssession>ここでは、すべてのログオンしているユーザーを確認してください。</burl> ";
$__emessage['login_error'] = "ログインエラー";
$__emessage['file_exists'] = "ファイル(s) [%s] 既に存在しています。あなたが貼り付けることはできません...";
$__emessage['cannot_unzip_in_root'] = "あなたは、ルートディレクトリにファイルを抽出することはできません(root). 解凍後のディレクトリを指定してください。";
$__emessage['nouser_email'] = "Email ユーザーの連絡先アドレスと一致することができません。";
$__emessage['session_expired'] = "セッション失敗";
$__emessage['e_password'] = "間違ったパスワード";
$__emessage['is_demo'] = "[%s] デモ版では禁止されています。";
$__emessage['user_create'] = "ユーザー [%s] 作成できません、別の名前を試してみてください";
$__emessage['switch_done'] = "変換サーバ・プロセスは、変換が行われたときにメッセージを送信します、バックグラウンドで実行されます";
$__emessage['mis_changed'] = "ディスプレイ構成変換が成功。";
$__emessage['password_sent'] = "パスワードがリセットされ、正常に送信されました";
$__emessage['added_successfully'] = "[%s] 追加に成功しました。";
$__emessage['backup_has_been_scheduled'] = "バックアップがある.......Eメール通知が完了します！";
$__emessage['update_scheduled'] = "バックグラウンドで実行されている更新します。あなたは、更新が完了したかどうかを確認するためにページを更新することができます。";
$__emessage['restore_has_been_scheduled'] = "バックグラウンドで実行されている復元します。Eメール通知が完了します！。";
$__emessage['same_dns'] = "サーバーからマスターサーバーは同じではありません。";
$__emessage['user_exists'] = "ユーザー [%s] すでに存在しています。";
$__emessage['mysql_error'] = "Mysql エラー、データベース： [%s]";
$__emessage['this_domain_does_not_resolve_to_this_ip'] = "IPドメイン名を作るためにバインドされ、ドメイン名は、IPをバインドする必要があります。 そうしないと、ドメインは機能しなくなります。 このIPをマップするドメインは、IPに戻って解決されないため、IPのデフォルトドメインとして設定することはできません。";
$__emessage['dns_conflict'] = "DNSエラーは、ドメイン名のセットにつながる追加することはできません。あなたのDNSテンプレートをチェックして確認してください。このメッセージは、DNSサーバからです： [%s]";
$__emessage['add_without_www'] = "メインドメインのみをdomain.comの形式で追加する必要があります。 [b] www [/ b]サブドメインが自動的に追加されます。 ドメインの作成時に[b] www [/ b]を追加しないでください。";
$__emessage['could_not_connect_to_db'] = "エラーが記録されている、管理者に連絡してください：データベースに接続できません";
$__emessage['e_no_dbadmin_entries'] = "この特定のサーバーに対して構成されたデータベース管理者エントリはありません。 設定するには管理者に連絡してください。";
$__emessage['please_add_one_domain_for_owner_mode'] = "ドメイン所有者モードに切り替えるには、少なくとも1つのドメインが必要です。 ドメインを追加するには<url:a=addform&c=domain>clicking here </url>.";
$__emessage['e_no_dbadmin_entries_admin'] = "この特定のサーバーに対して構成されたデータベース管理者エントリはありません。 このサーバーのサーバーセクションに移動し、Dbadminリンクをクリックし、この特定のマシンのデータベース管理ユーザーとパスワードとデータベースの種類を追加する必要があります。";
$__emessage['mail_server_name_not_set'] = "メールサーバーの識別名が設定されていません。 これは、ホットメールのような多くのパブリックメールサーバーがサーバーからのメールを拒否することを意味します。 クリック <url:k[class]=pserver&k[nname]=localhost&a=updateform&sa=update&o=servermail> here to set it. </url>";
$__emessage['dns_template_inconsistency'] = "あなたが選択したDNSテンプレートは、選択したサーバーと一致しません。 たとえば、DNS内のipaddressがWebサーバーにまったく見つからないことがあります。 戻って、サーバーセットアップと一致するパラメータを持つdnsテンプレートを作成してください。";
$__emessage['adding_cron_failed'] = "失敗したため、タイマーを追加 [%s]. それを削除してから外観を追加してください。";
$__emessage['se_submit_running_background'] = "検索エンジンの提出は、バックグラウンドで実行されています。連絡先のメールにメッセージを送信が完了します。";
$__emessage['err_no_dns_template'] = "DNSテンプレートシステムは。あなたは、少なくともテンプレートの後にドメイン名とDNSクライアントを追加することができるよう追加する必要はありません。クリックしてください<url:a=addform&c=dnstemplate> ここではDNSテンプレートを追加します </url></p> ";
$__emessage['certificate_key_file_empty'] = "証明書とキーファイルの選択は、あなたが最初に作成またはSSLを開始する前に、ファイルをアップロードする必要があり、空であります";